# Generated by Django 3.0.4 on 2020-03-18 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a place name', max_length=200)),
                ('geoPosition', models.CharField(help_text='Enter a place geo position', max_length=20)),
                ('climate', models.CharField(help_text='Enter a place climate', max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Country')),
                ('nations', models.ManyToManyField(max_length=200, to='backend.Nation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your name', max_length=200)),
                ('login', models.CharField(help_text='Enter your login', max_length=200)),
                ('password', models.CharField(help_text='Enter your password', max_length=200)),
                ('userPlaces', models.ManyToManyField(help_text='Choose places', to='backend.Place')),
            ],
        ),
    ]
