# Generated by Django 3.0.4 on 2020-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200318_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='geoPosition',
            field=models.CharField(help_text='Enter a place geo position', max_length=200),
        ),
    ]
