# Generated by Django 3.0.4 on 2020-03-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200318_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='nations',
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
    ]
