# Generated by Django 3.0.4 on 2020-03-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200318_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
