# Generated by Django 3.0.4 on 2020-03-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200328_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
